name: ecb_fx
description: Foreign Exchange (FX) rates from the European Central Bank.
version: 0.0.1

author: Istvan Soos <istvan.soos@agilord.com>
homepage: https://github.com/agilord/ecb_fx

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  decimal: ^0.1.4
  http_client: ^0.2.2
  xml: ^2.5.0

dev_dependencies:
  test: ^0.12.0
