name: ecb_fx
description: Current, 90-day and historical Foreign Exchange (FX) rates from the European Central Bank.
version: 0.1.1

author: Istvan Soos <istvan.soos@agilord.com>
homepage: https://github.com/agilord/ecb_fx

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  decimal: ^0.3.0
  http_client: ^0.5.0
  xml: ^3.2.0

dev_dependencies:
  test: ^1.0.0
